import Odds from '../../core/Odds';

export default {
    'S_1X2_1': Odds.WIN_1,
    'S_1X2_2': Odds.WIN_2,
    'S_1X2_X': Odds.WIN_X,
    'S_DC_1X': Odds.WIN_1X,
    'S_DC_12': Odds.WIN_12,
    'S_DC_X2': Odds.WIN_2X,
    'S_OU': {
        items: {
            O: Odds.GOALS_OVER,
            U: Odds.GOALS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'S_DNB_1': Odds.AH1_.replace(':value', '0'),
    'S_DNB_2': Odds.AH2_.replace(':value', '0'),
    'S_OE_EV': Odds.GOALS_EVEN,
    'S_OE_OD': Odds.GOALS_ODD,
    'S_GGNG_N': Odds.BOTH_TEAMS_SCORE_NO,
    'S_GGNG_Y': Odds.BOTH_TEAMS_SCORE_YES,
    'S_12HND': {
        items: {
            '2H': Odds.AH2_,
            '1H': Odds.AH1_,
        },
        replace: true,
        asian: true,
    },
    'S_OU1T': {
        items: {
            O: Odds.FIRST_HALF_GOALS_OVER,
            U: Odds.FIRST_HALF_GOALS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'S_DNB1T_1': Odds.FIRST_HALF_ASIAN_HANDICAP_1_.replace(':value', '0'),
    'S_DNB1T_2': Odds.FIRST_HALF_ASIAN_HANDICAP_2_.replace(':value', '0'),
    'S_GGNG1T_Y': Odds.FIRST_HALF_BOTH_TEAMS_SCORE_YES,
    'S_GGNG1T_N': Odds.FIRST_HALF_BOTH_TEAMS_SCORE_NO,
    'S_OUHOME1T': {
        items: {
            O: Odds.E1_FIRST_HALF_GOALS_OVER,
            U: Odds.E1_FIRST_HALF_GOALS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'S_OE1T_OD': Odds.FIRST_HALF_GOALS_ODD,
    'S_OE1T_EV': Odds.FIRST_HALF_GOALS_EVEN,
    'S_OU2T': {
        items: {
            O: Odds.SECOND_HALF_GOALS_OVER,
            U: Odds.SECOND_HALF_GOALS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'S_DNB2T_1': Odds.SECOND_HALF_ASIAN_HANDICAP_1_.replace(':value', '0'),
    'S_DNB2T_2': Odds.SECOND_HALF_ASIAN_HANDICAP_2_.replace(':value', '0'),
    'S_GGNG2T_Y': Odds.SECOND_HALF_BOTH_TEAMS_SCORE_YES,
    'S_GGNG2T_N': Odds.SECOND_HALF_BOTH_TEAMS_SCORE_NO,
    'S_OUHOME2T': {
        items: {
            O: Odds.E1_SECOND_HALF_GOALS_OVER,
            U: Odds.E1_SECOND_HALF_GOALS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'S_OUAWAY2T': {
        items: {
            O: Odds.E2_SECOND_HALF_GOALS_OVER,
            U: Odds.E2_SECOND_HALF_GOALS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'S_OE2T_OD': Odds.SECOND_HALF_GOALS_ODD,
    'S_OE2T_EV': Odds.SECOND_HALF_GOALS_EVEN,
    'S_OUCORNERS': {
        items: {
            O: Odds.CORNERS_TOTAL_OVER,
            U: Odds.CORNERS_TOTAL_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'S_OUCORNERS1T': {
        items: {
            O: Odds.FIRST_HALF_CORNERS_OVER,
            U: Odds.FIRST_HALF_CORNERS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'S_OUCORNERS2T': {
        items: {
            O: Odds.SECOND_HALF_CORNERS_OVER,
            U: Odds.SECOND_HALF_CORNERS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'S_OUBOOK': {
        items: {
            O: Odds.YELLOW_CARDS_TOTAL_OVER,
            U: Odds.YELLOW_CARDS_TOTAL_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'S_OUBOOK1T': {
        items: {
            O: Odds.FIRST_HALF_YELLOW_CARDS_TOTAL_OVER,
            U: Odds.FIRST_HALF_YELLOW_CARDS_TOTAL_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'S_HOMEOFF_Y': Odds.E1_RED_CARD_YES,
    'S_HOMEOFF_N': Odds.E1_RED_CARD_NO,
    'S_AWAYOFF_Y': Odds.E2_RED_CARD_YES,
    'S_AWAYOFF_N': Odds.E2_RED_CARD_NO,
    'S_1X2HND@-4_1H': Odds.EH1.replace(':value', '0:4'),
    'S_1X2HND@-4_2H': Odds.EH2.replace(':value', '0:4'),
    'S_1X2HND@-4_XH': Odds.EHX.replace(':value', '0:4'),
    'S_1X2HND@-3_1H': Odds.EH1.replace(':value', '0:3'),
    'S_1X2HND@-3_2H': Odds.EH2.replace(':value', '0:3'),
    'S_1X2HND@-3_XH': Odds.EHX.replace(':value', '0:3'),
    'S_1X2HND@-2_1H': Odds.EH1.replace(':value', '0:2'),
    'S_1X2HND@-2_2H': Odds.EH2.replace(':value', '0:2'),
    'S_1X2HND@-2_XH': Odds.EHX.replace(':value', '0:2'),
    'S_1X2HND@-1_1H': Odds.EH1.replace(':value', '0:1'),
    'S_1X2HND@-1_2H': Odds.EH2.replace(':value', '0:1'),
    'S_1X2HND@-1_XH': Odds.EHX.replace(':value', '0:1'),
    'S_1X2HND@4_1H': Odds.EH1.replace(':value', '4:0'),
    'S_1X2HND@4_2H': Odds.EH2.replace(':value', '4:0'),
    'S_1X2HND@4_XH': Odds.EHX.replace(':value', '4:0'),
    'S_1X2HND@3_1H': Odds.EH1.replace(':value', '3:0'),
    'S_1X2HND@3_2H': Odds.EH2.replace(':value', '3:0'),
    'S_1X2HND@3_XH': Odds.EHX.replace(':value', '3:0'),
    'S_1X2HND@2_1H': Odds.EH1.replace(':value', '2:0'),
    'S_1X2HND@2_2H': Odds.EH2.replace(':value', '2:0'),
    'S_1X2HND@2_XH': Odds.EHX.replace(':value', '2:0'),
    'S_1X2HND@1_1H': Odds.EH1.replace(':value', '1:0'),
    'S_1X2HND@1_2H': Odds.EH2.replace(':value', '1:0'),
    'S_1X2HND@1_XH': Odds.EHX.replace(':value', '1:0'),
    'S_12HND1T': {
        items: {
            '2H': Odds.FIRST_HALF_ASIAN_HANDICAP_2_,
            '1h': Odds.FIRST_HALF_ASIAN_HANDICAP_1_,
        },
        replace: true,
        asian: true,
    },
    'S_12HND2T': {
        items: {
            '2H': Odds.SECOND_HALF_ASIAN_HANDICAP_2_,
            '1h': Odds.SECOND_HALF_ASIAN_HANDICAP_1_,
        },
        replace: true,
        asian: true,
    },
    'S_HNDCORNER1T': {
        items: {
            '2H': Odds.FIRST_HALF_CORNERS__HANDICAP_2,
            '1h': Odds.FIRST_HALF_CORNERS__HANDICAP_1,
        },
        replace: true,
        asian: true,
    },
    'S_OUCORNERSHOME': {
        items: {
            HO: Odds.E1_CORNERS_TOTAL_OVER,
            HU: Odds.E1_CORNERS_TOTAL_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'S_OUCORNERSAWAY': {
        items: {
            AO: Odds.E2_CORNERS_TOTAL_OVER,
            AU: Odds.E2_CORNERS_TOTAL_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'S_HNDCORNER': {
        items: {
            '2H': Odds.CORNERS_HANDICAP_2,
            '1h': Odds.CORNERS_HANDICAP_1,
        },
        replace: true,
        asian: true,
    },
    // tennis
    'T_OUG': {
        items: {
            O: Odds.TOTAL_GAMES_OVER,
            U: Odds.TOTAL_GAMES_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'T_HND': {
        items: {
            2: Odds.HANDICAP_SET_2,
            1: Odds.HANDICAP_SET_1,
        },
        replace: true,
        asian: true,
    },
    'T_HNDGAMES': {
        items: {
            2: Odds.HANDICAP_GAMES_2,
            1: Odds.HANDICAP_GAMES_1,
        },
        replace: true,
        asian: true,
    },
    'T_OUHOME': {
        items: {
            O: Odds.E1_TOTAL_GAMES_OVER,
            U: Odds.E1_TOTAL_GAMES_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'T_OUAWAY': {
        items: {
            O: Odds.E2_TOTAL_GAMES_OVER,
            U: Odds.E2_TOTAL_GAMES_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'T_OU1S': {
        items: {
            O: Odds.FIRST_SET_GAMES_OVER,
            U: Odds.FIRST_SET_GAMES_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'T_121P_1': Odds.FIRST_SET_WIN_1,
    'T_121P_2': Odds.FIRST_SET_WIN_2,
    'T_122P_1': Odds.SECOND_SET_WIN_1,
    'T_122P_2': Odds.SECOND_SET_WIN_2,
    'T_12_1': Odds.WIN_NE_1,
    'T_12_2': Odds.WIN_NE_2,
    'T_OEG_EV': Odds.GAMES_EVEN,
    'T_OEG_OD': Odds.GAMES_ODD,
    // BASKETBALL

    'B_OUHND1P': {
        items: {
            O: Odds.FIRST_QUARTER_POINTS_OVER,
            U: Odds.FIRST_QUARTER_POINTS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'B_OUHND1T': {
        items: {
            O: Odds.FIRST_HALF_POINTS_OVER,
            U: Odds.FIRST_HALF_POINTS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'B_12HND': {
        items: {
            '2H': Odds.HANDICAP_2_INCLUDING_ALL,
            '1H': Odds.HANDICAP_1_INCLUDING_ALL,
        },
        replace: true,
        asian: true,
    },
    'B_12HND1T': {
        items: {
            '2H': Odds.FIRST_HALF_ASIAN_HANDICAP_2_,
            '1H': Odds.FIRST_HALF_ASIAN_HANDICAP_1_,
        },
        replace: true,
        asian: true,
    },
    'B_DC_X2': Odds.WIN_2X,
    'B_DC_1X': Odds.WIN_1X,
    'B_DC_12': Odds.WIN_12,
    'B_OERT_EV': Odds.POINTS_EVEN,
    'B_OERT_OD': Odds.POINTS_ODD,
    'B_OE1P_OD': Odds.FIRST_QUARTER_ODD,
    'B_OE1P_EV': Odds.FIRST_QUARTER_EVEN,
    'B_OUHND': {
        items: {
            O: Odds.POINTS_OVER,
            U: Odds.POINTS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'B_DNB1T_2': Odds.FIRST_HALF_ASIAN_HANDICAP_2_.replace(':value', '0'),
    'B_DNB1T_1': Odds.FIRST_HALF_ASIAN_HANDICAP_1_.replace(':value', '0'),
    'B_OE4P_EV': Odds.FOURTH_QUARTER_EVEN,
    'B_OE4P_OD': Odds.FOURTH_QUARTER_ODD,
    'B_DC1T_1X': Odds.FIRST_HALF_WIN_1X,
    'B_DC1T_X2': Odds.FIRST_HALF_WIN_2X,
    'B_DC1T_12': Odds.FIRST_HALF_WIN_12,
    'B_OE3P_EV': Odds.THIRD_QUARTER_EVEN,
    'B_OE3P_OD': Odds.THIRD_QUARTER_ODD,
    'B_1X21P_1': Odds.FIRST_QUARTER_WIN_1,
    'B_1X21P_2': Odds.FIRST_QUARTER_WIN_2,
    'B_1X21P_X': Odds.FIRST_QUARTER_WIN_X,
    'B_1X23P_1': Odds.THIRD_QUARTER_WIN_1,
    'B_1X23P_2': Odds.THIRD_QUARTER_WIN_2,
    'B_1X23P_X': Odds.THIRD_QUARTER_WIN_X,
    'B_OE2T_EV': Odds.SECOND_HALF_POINTS_EVEN,
    'B_OE2T_ODD': Odds.SECOND_HALF_POINTS_ODD,
    'B_12_2': Odds.WIN_NE_2,
    'B_12_1': Odds.WIN_NE_1,
    'B_1X24P_X': Odds.FOURTH_QUARTER_WIN_X,
    'B_1X24P_1': Odds.FOURTH_QUARTER_WIN_1,
    'B_1X24P_2': Odds.FOURTH_QUARTER_WIN_2,
    'B_1X22P_1': Odds.SECOND_HALF_WIN_1,
    'B_1X22P_2': Odds.SECOND_HALF_WIN_2,
    'B_1X22P_X': Odds.SECOND_HALF_WIN_X,
    'B_OEHOMERT_OD': Odds.E1_POINTS_ODD,
    'B_OEHOMERT_EV': Odds.E1_POINTS_EVEN,
    'B_OE2P_OD': Odds.SECOND_QUARTER_ODD,
    'B_OE2P_EV': Odds.SECOND_QUARTER_EVEN,
    'B_OEAWAYRT_OD': Odds.E2_POINTS_ODD,
    'B_OEAWAYRT_EV': Odds.E2_POINTS_EVEN,
    'B_1X21T_1': Odds.FIRST_HALF_WIN_1,
    'B_1X21T_2': Odds.FIRST_HALF_WIN_2,
    'B_1X21T_X': Odds.FIRST_HALF_WIN_X,
    'B_1X2_1': Odds.WIN_1,
    'B_1X2_2': Odds.WIN_2,
    'B_1X2_X': Odds.WIN_X,
    'B_OE1T_EV': Odds.FIRST_HALF_POINTS_EVEN,
    'B_OE1T_OD': Odds.FIRST_HALF_POINTS_ODD,
    'B_OT_Y': Odds.HAS_EXTRA_TIME_YES,
    'B_OT_N': Odds.HAS_EXTRA_TIME_NO,
    // american football
    'F_12HND': {
        items: {
            2: Odds.HANDICAP_2_INCLUDING_ALL,
            1: Odds.HANDICAP_1_INCLUDING_ALL,
        },
        replace: true,
        asian: true,
    },
    'F_OERT_EV': Odds.POINTS_EVEN,
    'F_OERT_OD': Odds.POINTS_ODD,
    'F_OUAWAY': {
        items: {
            O: Odds.E2_POINTS_OVER,
            U: Odds.E2_POINTS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'F_OUHOME': {
        items: {
            O: Odds.E1_POINTS_OVER,
            U: Odds.E1_POINTS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'F_OU': {
        items: {
            O: Odds.POINTS_OVER,
            U: Odds.POINTS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'F_OT_Y': Odds.HAS_EXTRA_TIME_YES,
    'F_OT_N': Odds.HAS_EXTRA_TIME_NO,
    'F_OU4P': {
        items: {
            O: Odds.FOURTH_QUARTER_POINTS_OVER,
            U: Odds.FOURTH_QUARTER_POINTS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'F_12_2': Odds.WIN_NE_2,
    'F_12_1': Odds.WIN_NE_1,
    'F_OU2T': {
        items: {
            O: Odds.SECOND_HALF_POINTS_OVER,
            U: Odds.SECOND_HALF_POINTS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'F_OU3P': {
        items: {
            O: Odds.THIRD_QUARTER_POINTS_OVER,
            U: Odds.THIRD_QUARTER_POINTS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'F_12HND1T': {
        items: {
            2: Odds.FIRST_HALF_ASIAN_HANDICAP_2_,
            1: Odds.FIRST_HALF_ASIAN_HANDICAP_1_,
        },
        replace: true,
        asian: true,
    },
    'F_OU1T': {
        items: {
            O: Odds.FIRST_HALF_POINTS_OVER,
            U: Odds.FIRST_HALF_POINTS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'F_OU2P': {
        items: {
            O: Odds.SECOND_QUARTER_POINTS_OVER,
            U: Odds.SECOND_QUARTER_POINTS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'F_OU1P': {
        items: {
            O: Odds.FIRST_QUARTER_POINTS_OVER,
            U: Odds.FIRST_QUARTER_POINTS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'F_12HND3P': {
        items: {
            2: Odds.THIRD_QUARTER_H2_,
            1: Odds.THIRD_QUARTER_H1_,
        },
        replace: true,
        asian: true,
    },
    'F_12HND1P': {
        items: {
            2: Odds.FIRST_QUARTER_H2_,
            1: Odds.FIRST_QUARTER_H1_,
        },
        replace: true,
        asian: true,
    },
    'F_12HND4P': {
        items: {
            2: Odds.FOURTH_QUARTER_H2_,
            1: Odds.FOURTH_QUARTER_H1_,
        },
        replace: true,
        asian: true,
    },
    'F_12HND2P': {
        items: {
            2: Odds.SECOND_QUARTER_H2_,
            1: Odds.SECOND_QUARTER_H1_,
        },
        replace: true,
        asian: true,
    },
    'F_12HND2T': {
        items: {
            2: Odds.SECOND_HALF_ASIAN_HANDICAP_2_,
            1: Odds.SECOND_HALF_ASIAN_HANDICAP_1_,
        },
        replace: true,
        asian: true,
    },
    // HOCKEY
    'IH_OE3P_EV': Odds.THIRD_HALF_GOALS_EVEN,
    'IH_OE3P_OD': Odds.THIRD_HALF_GOALS_ODD,
    'IH_12HND': {
        items: {
            '2H': Odds.HANDICAP_2_INCLUDING_ALL,
            '1H': Odds.HANDICAP_1_INCLUDING_ALL,
        },
        replace: true,
        asian: true,
    },
    'IH_12HND3P': {
        items: {
            '2H': Odds.THIRD_HALF_ASIAN_HANDICAP_2_,
            '1H': Odds.THIRD_HALF_ASIAN_HANDICAP_1_,
        },
        replace: true,
        asian: true,
    },
    'IH_OU3P': {
        items: {
            O: Odds.THIRD_HALF_GOALS_OVER,
            U: Odds.THIRD_HALF_GOALS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'IH_OU2P': {
        items: {
            O: Odds.SECOND_HALF_GOALS_OVER,
            U: Odds.SECOND_HALF_GOALS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'IH_OU1P': {
        items: {
            O: Odds.FIRST_HALF_GOALS_OVER,
            U: Odds.FIRST_HALF_GOALS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'IH_OUHND': {
        items: {
            O: Odds.GOALS_OVER,
            U: Odds.GOALS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'IH_OE_EV': Odds.GOALS_EVEN,
    'IH_OE_OD': Odds.GOALS_ODD,
    'IH_GGNG1P_N': Odds.FIRST_HALF_BOTH_TEAMS_SCORE_NO,
    'IH_GGNG1P_Y': Odds.FIRST_HALF_BOTH_TEAMS_SCORE_YES,
    'IH_GGNG_N': Odds.BOTH_TEAMS_SCORE_NO,
    'IH_GGNG_Y': Odds.BOTH_TEAMS_SCORE_YES,
    'IH_OE2P_OD': Odds.SECOND_QUARTER_ODD,
    'IH_OE2P_EV': Odds.SECOND_QUARTER_EVEN,
    'IH_1X2_1': Odds.WIN_1,
    'IH_1X2_X': Odds.WIN_X,
    'IH_1X2_2': Odds.WIN_2,
    'IH_12HND2P': {
        items: {
            '2H': Odds.SECOND_HALF_ASIAN_HANDICAP_2_,
            '1H': Odds.SECOND_HALF_ASIAN_HANDICAP_1_,
        },
        replace: true,
        asian: true,
    },
    'IH_1X22P_1': Odds.SECOND_HALF_WIN_1,
    'IH_1X22P_X': Odds.SECOND_HALF_WIN_X,
    'IH_1X22P_2': Odds.SECOND_HALF_WIN_2,
    'IH_12HND1P': {
        items: {
            '2H': Odds.FIRST_HALF_ASIAN_HANDICAP_2_,
            '1H': Odds.FIRST_HALF_ASIAN_HANDICAP_1_,
        },
        replace: true,
        asian: true,
    },
    'IH_1X21P_1': Odds.FIRST_HALF_WIN_1,
    'IH_1X21P_X': Odds.FIRST_HALF_WIN_X,
    'IH_1X21P_2': Odds.FIRST_HALF_WIN_2,
    'IH_OUHOME': {
        items: {
            O: Odds.E1_GOALS_OVER,
            U: Odds.E1_GOALS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'IH_DC1P_12': Odds.FIRST_HALF_WIN_12,
    'IH_DC1P_1X': Odds.FIRST_HALF_WIN_1X,
    'IH_DC1P_X2': Odds.FIRST_HALF_WIN_2X,
    'IH_OE1P_OD': Odds.FIRST_HALF_GOALS_ODD,
    'IH_OE1P_EV': Odds.FIRST_HALF_GOALS_EVEN,
    'IH_DC_X2': Odds.WIN_2X,
    'IH_DC_1X': Odds.WIN_1X,
    'IH_DC_12': Odds.WIN_12,
    'IH_1X23P_X': Odds.THIRD_HALF_WIN_X,
    'IH_1X23P_1': Odds.THIRD_HALF_WIN_1,
    'IH_1X23P_2': Odds.THIRD_HALF_WIN_2,
    'IH_DC2P_12': Odds.SECOND_HALF_WIN_12,
    'IH_DC2P_1X': Odds.SECOND_HALF_WIN_1X,
    'IH_DC2P_X2': Odds.SECOND_HALF_WIN_2X,
    'IH_DC3P_12': Odds.THIRD_HALF_WIN_12,
    'IH_DC3P_1X': Odds.THIRD_HALF_WIN_1X,
    'IH_DC3P_X2': Odds.THIRD_HALF_WIN_2X,
    'IH_DNB1P_2': Odds.FIRST_HALF_ASIAN_HANDICAP_2_.replace(':value', '0'),
    'IH_DNB1P_1': Odds.FIRST_HALF_ASIAN_HANDICAP_1_.replace(':value', '0'),
    'IH_DNB2P_2': Odds.SECOND_HALF_ASIAN_HANDICAP_2_.replace(':value', '0'),
    'IH_DNB2P_1': Odds.SECOND_HALF_ASIAN_HANDICAP_1_.replace(':value', '0'),
    'IH_OUAWAY': {
        items: {
            O: Odds.E2_GOALS_OVER,
            U: Odds.E2_GOALS_UNDER,
        },
        replace: true,
        over_under: true,
    },
    'IH_1X2HND@-4_1H': Odds.EH1.replace(':value', '0:4'),
    'IH_1X2HND@-4_2H': Odds.EH2.replace(':value', '0:4'),
    'IH_1X2HND@-4_XH': Odds.EHX.replace(':value', '0:4'),
    'IH_1X2HND@-3_1H': Odds.EH1.replace(':value', '0:3'),
    'IH_1X2HND@-3_2H': Odds.EH2.replace(':value', '0:3'),
    'IH_1X2HND@-3_XH': Odds.EHX.replace(':value', '0:3'),
    'IH_1X2HND@-2_1H': Odds.EH1.replace(':value', '0:2'),
    'IH_1X2HND@-2_2H': Odds.EH2.replace(':value', '0:2'),
    'IH_1X2HND@-2_XH': Odds.EHX.replace(':value', '0:2'),
    'IH_1X2HND@-1_1H': Odds.EH1.replace(':value', '0:1'),
    'IH_1X2HND@-1_2H': Odds.EH2.replace(':value', '0:1'),
    'IH_1X2HND@-1_XH': Odds.EHX.replace(':value', '0:1'),
    'IH_1X2HND@4_1H': Odds.EH1.replace(':value', '4:0'),
    'IH_1X2HND@4_2H': Odds.EH2.replace(':value', '4:0'),
    'IH_1X2HND@4_XH': Odds.EHX.replace(':value', '4:0'),
    'IH_1X2HND@3_1H': Odds.EH1.replace(':value', '3:0'),
    'IH_1X2HND@3_2H': Odds.EH2.replace(':value', '3:0'),
    'IH_1X2HND@3_XH': Odds.EHX.replace(':value', '3:0'),
    'IH_1X2HND@2_1H': Odds.EH1.replace(':value', '2:0'),
    'IH_1X2HND@2_2H': Odds.EH2.replace(':value', '2:0'),
    'IH_1X2HND@2_XH': Odds.EHX.replace(':value', '2:0'),
    'IH_1X2HND@1_1H': Odds.EH1.replace(':value', '1:0'),
    'IH_1X2HND@1_2H': Odds.EH2.replace(':value', '1:0'),
    'IH_1X2HND@1_XH': Odds.EHX.replace(':value', '1:0'),

};
